apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-app
  labels:
    app: nginpython-web-appx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-web-app
  template:
    metadata:
      labels:
        app: python-web-app
    spec:
      containers:
      - name: python-app
        image: bhavin7/python-web-app-demo:v1
        ports:
        - containerPort: 8000
